apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: tattack99/search-service:search-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
          env:
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: journaldb-secret
                  key: QUARKUS_DATASOURCE_PASSWORD
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: journaldb-secret
                  key: QUARKUS_DATASOURCE_USERNAME
            - name: QUARKUS_DATASOURCE_REACTIVE_URL
              valueFrom:
                secretKeyRef:
                  name: journaldb-secret
                  key: QUARKUS_DATASOURCE_REACTIVE_URL

---
apiVersion: v1
kind: Service
metadata:
  name: search-service-service
spec:
  type: NodePort
  selector:
    app: search-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30003
